# -*- coding: utf-8 -*-
"""Cópia de Exerciciopy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18uau--rPBXngXnlY1YERRaGHqVEzLpuV
"""

for i in range(16):

  print(i * 5)

#Exercicio 1
numero = int(input("Digite um número:"))

if numero % 2 == 0:
    print("O número é par")
else:
    print("O número é ímpar")

#Exercicio 2
idade = int(input("Digite sua idade:"))

if idade >= 65:
    print("Você tem gratuidade no transporte")
else:
    print("Você não tem transporte gratuito")

#Exercicio 3
import numpy as np
nota1 = float(input("Digite a primeira nota:"))
nota2 = float(input("Digite a segunda nota:"))

notas = np.array([nota1, nota2])
media = np.mean(notas)
if media >= 7:
    print("Aprovado")
else:
    print("Reprovado")

#Exercicio 4

preco_oculos = 200.00

idade = int(input("Digite sua idade:"))
if idade < 10:
  desconto = 10
elif idade > 80:
  desconto = 80
else: desconto = idade


valor_desconto = preco_oculos * (desconto / 100)
preco_total = preco_oculos - valor_desconto
print(f'Você recebeu um valor de desconto:{desconto} %')
print(f'O valor total a pagar é {int(preco_total)},00')

#Exercicio 5
salario_atual = float(input("Digite seu salário atual:"))
if salario_atual < 1500.00:
    aumento = 25
elif 1500.00 <= salario_atual < 1999.99:
    aumento = 20
elif 2000.00 <= salario_atual < 2999.99:
    aumento = 15
elif 3000.00 <= salario_atual < 4999.99:
    aumento = 10
else:
    if salario_atual >= 5000.00:
        aumento = 5
print(f'O valor do aumento é de {aumento} %')
print(f'O novo salário é de {int(salario_atual + (salario_atual * (aumento / 100)))}')
print(f'O salário reajustado é de {int(salario_atual)}')

numero1 = int(input("Digite o primeiro número:"))
numero2 = int(input("Digite o segundo número:"))
soma = numero1 + numero2
print(f'A soma dos números é {soma}')

numero1 = int(input("Digite o primeiro número:"))
numero2 = int(input("Digite o segundo número:"))
multiplicacao = numero1 * numero2
print(f'A Multiplicação  dos números é {multiplicacao}')

numero1 = int(input("Digite o primeiro número:"))
numero2 = int(input("Digite o segundo número:"))
divisao = numero1 / numero2
print(f'A Divisão dos números é {divisao}')

numero1 = int(input("Digite o primeiro número:"))
numero2 = int(input("Digite o segundo número:"))
divisao = numero1 - numero2
print(f'A Subtração dos números é {divisao}')

import numpy as np
nota1 = float(input("Digite a primeira nota:"))
nota2 = float(input("Digite a segunda nota:"))

notas = np.array([nota1, nota2])
media = np.mean(notas)
print(f'A média do aluno é {media}')

nome = input("Digite seu nome:")
idade = int(input("Digite sua idade:"))
peso = float(input("Digite seu peso:"))
altura = float(input("Digite sua altura:"))
imc = peso / (altura ** 2)
print(f'Seu nome é {nome} e tem {len(nome)} caracteres, você tem {idade} anos e nasceu no ano de {2024 - idade}. Você mede {altura} cm, pesa {peso} Kg e seu IMC é {imc}')

numero_secreto = random.raandit(0, 1000)
alternativas = 10

print('Bem vindo ao jogo da Adivinhação')
print('Adivinhe um numero de 0 a 10000')
print(f'Você tem {alternativas} tentativas')

for i in 'joao'[:-1]:
  print(i)

##Exercicio 1 Lista 3
import random
numero_sec = random.randint(0, 1000) # O pc escolhe um numero aleatorio
tentativas = 10 #Quantidade de tentativas

print('Bem vindo ao jogo do numero secreto')
print('Adivinhe um numero de 0 a 10000')
print(f'Você tem {tentativas} tentativas') #Printa na tela a quantidade de tentantivas restantantes

while tentativas > 0: ##Cria a Condição que se tentativas for maior que 0, o usuario tem que inputar um valor de 0 a 1000
    tentativa = int(input('Digite seu palpite:')) ## Input do usuario
    tentativas -= 1 # Retira uma tentantiva

    if tentativa == numero_sec: # Se tetantiva for = ao numero sec aleatorio
        print('Você acertou') ## Identificar que acertou , printar na tela e
        break ## Parar o programa
    else: #se nao
        print('Você errou') # Printar na tela que errou
        print(f'Você tem {tentativas} tentativas restantes.') # Printar na tela a quantidade de tentantivas restantes

#Exercicio 2 Lista 3
import random # importar o random para as voltas

def jogo_dados(n):
    somas = [0] * 13 # Realizar a multiplicão de 0 a 13

    for i in range(n):
        dado1 = random.randint(1, 6) # Escolher os numeros possiveis do dado 1
        dado2 = random.randint(1, 6) # Escolher os numeros possiveis do dado 2
        soma = dado1 + dado2 # Realizar a soma dos dois dados e resultados
        somas[soma] += 1 # Somar a quantidade de vezes que a soma ocorreu

    for i in range(2, 13): # Realizar a contagem e a soma de quantas vezes ocorreu
        print(f'A soma {i} ocorreu {somas[i]} vezes')

jogo_dados(10)

## Exercicio 3 Lista 3

vitoria = empate = derrota = 0
jogadas = ['r', 'p', 't'] # Adicionar a lista os dados que serão inputados

while True:
  jogador = input("[r] Pedra, [p] papel, [t] tesoura ou [s] sair:") #Pedir para o jogador inputar o que quer em sua jogada
  if jogador == 's': # se o jogador digitar s, irá sair do programa
    break

  computador = random.choice(jogadas) # Comando para o computador escolher de forma aleatoria a sua jogada
  print(f'O computador escolheu {computador}') # Irá printar qual a jogada que o pc escolheu

  if jogador == computador: # se o jogador inputar a mesma jogada do pc, irá printar empate
    print('Empate')
    empate += 1
  elif (jogador == 'r' and computador == 't') or (jogador == 'p' and computador == 'r') or (jogador == 't' and computador == 'p'): #Se as condiçoes forem verdadeiras, irá printar vitoria para o jogador
    print('Você ganhou')
    vitoria += 1
  else: # Se não ira printar derrota
    print('Você perdeu')
    derrota += 1

print(f"Vitórias: {vitoria}, Empates: {empate}, Derrotas: {derrota}") # Printa a quanta

#Exercicio 4 Lista 3
vida_jogador = 10
vida_pc = 10

while vida_jogador > 0 and vida_pc > 0: #Se a vida de ambos estiver maior que 0...
  escolha = input("Digite [f] para atacar com poder de fogo, Digite [v] para atacar com poder de vento ou [s] para sair:") # Sempre irá pedir para atacar novamente

  if escolha == 's': #Se o jogador escolher a string S, sempre irá finalizar o Programa
    break
  elif escolha == 'f': # Se escolher F, que é o poder de fogo
    vida_pc -= 4 #Conf do poder
    vida_jogador -=1 #Conf do poder

    print(f'Vida do PC: {vida_pc}') #Printar a vida atualizada do PC
  elif escolha == 'v': # Se escolher V que é o poder de vento, irá determinar as seguintes conf de poder
    vida_jogador -= 3 #conf de poder
    vida_pc -= 1 #conf de poder
    print(f'Vida do Jogador: {vida_jogador}') # Printar a vida atualizada do jogador

  else: #Se não colocar o poder correto: F ou V, Irá printar, opção invalidade
    print('Opção inválida')

if vida_jogador <= 0: #Se a vida do jogador for menor ou igual a 0, irá printar que perdeu
  print('Você perdeu')
else:
  print('Você ganhou') #Se a vida do jogador for maior que 0, irá printar que ganhou

#Exercicio 1 Lista 4
def funcao(nome): # Definindo o nome da funçao

   letras = nome[:4] # Informando que quero nas 4 primeiras letras
   final = letras + 'mon' # ADD o quero que venha apos a 4 localização da string
   return final # Fazendo um retorno da string final
nome = input(str("Digite seu nome:")) # Solicitando para o usuario digitar o seu nome
resultado = funcao(nome) #Ativando a função criada
print(resultado) # Printando o resultado da função

#Exercicio 2 Lista 4
def funcao(nome): # Definindo o nome da funçao

   letras = nome[:3] #Informando que quero a loc do objeto 3
   letras2 = nome[-3:]# informando que quero a loc do objeto -3
   final = letras + letras2 # Realizando as somas da variavel
   return final # Fazendo um retorno da string final
nome = input(str("Digite seu nome:")) # Solicitando para o usuario digitar o seu nome
resultado = funcao(nome) #Ativando a função criada
print(resultado) # Printando o resultado

#Exercicio 3 Lista 4
def funcao_1(texto):
  texto = texto.replace("a" , "4")
  texto = texto.replace("b" , "8")
  texto = texto.replace("e" , "3")
  texto = texto.replace("i" , "1")
  texto = texto.replace("o" , "0")
  texto = texto.replace("t" , "7")
  return texto
nomes = input(str("Digite seu nome:"))
resultado_1 = funcao_1(nomes)
print(resultado_1)