# -*- coding: utf-8 -*-
"""Cópia de Exerciciopy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18uau--rPBXngXnlY1YERRaGHqVEzLpuV
"""

for i in range(16):

  print(i * 5)

#Exercicio 1
numero = int(input("Digite um número:"))

if numero % 2 == 0:
    print("O número é par")
else:
    print("O número é ímpar")

#Exercicio 2
idade = int(input("Digite sua idade:"))

if idade >= 65:
    print("Você tem gratuidade no transporte")
else:
    print("Você não tem transporte gratuito")

#Exercicio 3
import numpy as np
nota1 = float(input("Digite a primeira nota:"))
nota2 = float(input("Digite a segunda nota:"))

notas = np.array([nota1, nota2])
media = np.mean(notas)
if media >= 7:
    print("Aprovado")
else:
    print("Reprovado")

#Exercicio 4

preco_oculos = 200.00

idade = int(input("Digite sua idade:"))
if idade < 10:
  desconto = 10
elif idade > 80:
  desconto = 80
else: desconto = idade


valor_desconto = preco_oculos * (desconto / 100)
preco_total = preco_oculos - valor_desconto
print(f'Você recebeu um valor de desconto:{desconto} %')
print(f'O valor total a pagar é {int(preco_total)},00')

#Exercicio 5
salario_atual = float(input("Digite seu salário atual:"))
if salario_atual < 1500.00:
    aumento = 25
elif 1500.00 <= salario_atual < 1999.99:
    aumento = 20
elif 2000.00 <= salario_atual < 2999.99:
    aumento = 15
elif 3000.00 <= salario_atual < 4999.99:
    aumento = 10
else:
    if salario_atual >= 5000.00:
        aumento = 5
print(f'O valor do aumento é de {aumento} %')
print(f'O novo salário é de {int(salario_atual + (salario_atual * (aumento / 100)))}')
print(f'O salário reajustado é de {int(salario_atual)}')

numero1 = int(input("Digite o primeiro número:"))
numero2 = int(input("Digite o segundo número:"))
soma = numero1 + numero2
print(f'A soma dos números é {soma}')

numero1 = int(input("Digite o primeiro número:"))
numero2 = int(input("Digite o segundo número:"))
multiplicacao = numero1 * numero2
print(f'A Multiplicação  dos números é {multiplicacao}')

numero1 = int(input("Digite o primeiro número:"))
numero2 = int(input("Digite o segundo número:"))
divisao = numero1 / numero2
print(f'A Divisão dos números é {divisao}')

numero1 = int(input("Digite o primeiro número:"))
numero2 = int(input("Digite o segundo número:"))
divisao = numero1 - numero2
print(f'A Subtração dos números é {divisao}')

import numpy as np
nota1 = float(input("Digite a primeira nota:"))
nota2 = float(input("Digite a segunda nota:"))

notas = np.array([nota1, nota2])
media = np.mean(notas)
print(f'A média do aluno é {media}')

nome = input("Digite seu nome:")
idade = int(input("Digite sua idade:"))
peso = float(input("Digite seu peso:"))
altura = float(input("Digite sua altura:"))
imc = peso / (altura ** 2)
print(f'Seu nome é {nome} e tem {len(nome)} caracteres, você tem {idade} anos e nasceu no ano de {2024 - idade}. Você mede {altura} cm, pesa {peso} Kg e seu IMC é {imc}')

numero_secreto = random.raandit(0, 1000)
alternativas = 10

print('Bem vindo ao jogo da Adivinhação')
print('Adivinhe um numero de 0 a 10000')
print(f'Você tem {alternativas} tentativas')

for i in 'joao'[:-1]:
  print(i)

##Exercicio 1 Lista 3
import random
numero_sec = random.randint(0, 1000)
tentativas = 10

print('Bem vindo ao jogo do numero secreto')
print('Adivinhe um numero de 0 a 10000')
print(f'Você tem {tentativas} tentativas')

while tentativas > 0:
    tentativa = int(input('Digite seu palpite:'))
    tentativas -= 1

    if tentativa == numero_sec:
        print('Você acertou')
        break
    else:
        print('Você errou')
        print(f'Você tem {tentativas} tentativas restantes.')

#Exercicio 2 Lista 3
import random

def jogo_dados(n):
    somas = [0] * 13

    for i in range(n):
        dado1 = random.randint(1, 6)
        dado2 = random.randint(1, 6)
        soma = dado1 + dado2
        somas[soma] += 1

    for i in range(2, 13):
        print(f'A soma {i} ocorreu {somas[i]} vezes')

jogo_dados(10)

## Exercicio 3 Lista 3
import random

vitoria = empate = derrota = 0
jogadas = ['r', 'p', 't']

while True:
  jogador = input("[r] Pedra, [p] papel, [t] tesoura ou [s] sair:")
  if jogador == 's':
    break

  computador = random.choice(jogadas)
  print(f'O computador escolheu {computador}')

  if jogador == computador:
    print('Empate')
    empate += 1
  elif (jogador == 'r' and computador == 't') or (jogador == 'p' and computador == 'r') or (jogador == 't' and computador == 'p'):
    print('Você ganhou')
    vitoria += 1
  else:
    print('Você perdeu')
    derrota += 1

print(f"Vitórias: {vitoria}, Empates: {empate}, Derrotas: {derrota}")

#Exercicio 4 Lista 3
vida_jogador = 10
vida_pc = 10

while vida_jogador > 0 and vida_pc > 0:
  escolha = input("Digite [f] para atacar com poder de fogo, Digite [v] para atacar com poder de vento ou [s] para sair:")

  if escolha == 's':
    break
  elif escolha == 'f':
    vida_pc -= 4
    vida_jogador -=1

    print(f'Vida do PC: {vida_pc}')
  elif escolha == 'v':
    vida_jogador -= 3
    vida_pc -= 1
    print(f'Vida do Jogador: {vida_jogador}')

  else:
    print('Opção inválida')

if vida_jogador <= 0:
  print('Você perdeu')
else:
  print('Você ganhou')